### ISSUE TITLE
Issues on Fuse 36.1?

### ISSUE THREAD

**Issue by Craigtut** [Sunjammer/nfuse#24]
I'm having issues getting this to even start to work. I've begun a new example project just to test on and get a long list of errors upon build of the project. I've installed lodash using npm as a test, used nfuse, but get a long list of errors upon building the preview.

This is an example of the errors:

`
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(4818): E3114: There is no identifier named 'Binding' accessible in this scope. Did you mean 'Binding' (as in Fuse.Binding) or 'Binding' (as in Fuse.Binding)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(4818,1): Error E3114: There is no identifier named 'Binding' accessible in this scope. Did you mean 'Binding' (as in Fuse.Binding) or 'Binding' (as in Fuse.Binding)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(4818): E3111: Fuse.Scripting does not contain type or namespace 'IScriptObject'. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(4818,1): Error E3111: Fuse.Scripting does not contain type or namespace 'IScriptObject'. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(7753): E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(7753,1): Error E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(7753): E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(7753,1): Error E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(11): E3114: There is no identifier named 'Behavior' accessible in this scope. Did you mean 'Behavior' (as in Fuse.Behavior) or 'Behavior' (as in Fuse.Behavior)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(11,1): Error E3114: There is no identifier named 'Behavior' accessible in this scope. Did you mean 'Behavior' (as in Fuse.Behavior) or 'Behavior' (as in Fuse.Behavior)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(163): E3114: There is no identifier named 'UnhandledExceptionArgs' accessible in this scope. Did you mean 'UnhandledExceptionArgs' (as in Fuse.UnhandledExceptionArgs) or 'UnhandledExceptionArgs' (as in Fuse.UnhandledExceptionArgs)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(163,1): Error E3114: There is no identifier named 'UnhandledExceptionArgs' accessible in this scope. Did you mean 'UnhandledExceptionArgs' (as in Fuse.UnhandledExceptionArgs) or 'UnhandledExceptionArgs' (as in Fuse.UnhandledExceptionArgs)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(435): E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(435,1): Error E3114: There is no identifier named 'Node' accessible in this scope. Did you mean 'Node' (as in Fuse.Node)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(692): E3114: There is no identifier named 'Diagnostic' accessible in this scope. Did you mean 'Diagnostic' (as in Fuse.Diagnostic) or 'Diagnostic' (as in Fuse.Diagnostic)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(692,1): Error E3114: There is no identifier named 'Diagnostic' accessible in this scope. Did you mean 'Diagnostic' (as in Fuse.Diagnostic) or 'Diagnostic' (as in Fuse.Diagnostic)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(2119): E3114: There is no identifier named 'VisualEventArgs' accessible in this scope. Did you mean 'VisualEventArgs' (as in Fuse.VisualEventArgs) or 'VisualEventArgs' (as in Fuse.VisualEventArgs)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
/Users/craig/Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(2119,1): Error E3114: There is no identifier named 'VisualEventArgs' accessible in this scope. Did you mean 'VisualEventArgs' (as in Fuse.VisualEventArgs) or 'VisualEventArgs' (as in Fuse.VisualEventArgs)? For example, try adding 'using Fuse;' to the top of the code file. Could you be missing a package reference?
../../Library/Application Support/Fusetools/Packages/FuseCore/0.44.2/$.uno(2237): E3114: There is no identifier named 'IScriptEvent' accessible in this scope. Did you mean 'IScriptEvent' (as in Fuse.Scripting.IScriptEvent) or 'IScriptEvent' (as in Fuse.Scripting.IScriptEvent)? For example, try adding 'using Fuse.Scripting;' to the top of the code file. Could you be missing a package reference?
`

The list of these errors goes on and on and on. Hopefully its just something that I'm not doing right, but it seems to be broken as of now.

**Comment by Sunjammer** [comment]
This should be fixed now :)

**Comment by jhsware** [comment]
This issue isn't fixed because the project wasn't built prior to release
